services:
  - type: web
    name: Free-Diamonds-in-TJK # Замените на имя вашего проекта
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    branch: main
